services:
  fake-news-detection:
    container_name: fake-news-detector

    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8501:8501"

    env_file:
      - .env

    restart: unless-stopped